### PR TITLE
Add tkinter GUI for neural song style transfer

### PR DESCRIPTION
**Pull request by ticklecatisback**
Add a tkinter-based GUI for neural song style transfer.

* **Add `tkinter_gui.py`**: Create a new script to provide a tkinter-based GUI for user interaction. The GUI allows users to select content and style audio files, specify the output file path, and start the style transfer process. It includes labels, entry fields, and buttons for these functionalities.
* **Modify `neuralaudiostyle.py`**: Refactor the main script into functions for reading audio spectrum, training style, and optimizing. Add a new function `perform_style_transfer(content, style, output)` to call the refactored functions. Remove the `argparse` code and replace it with function calls.
* **Update `README.md`**: Add a section "Using the tkinter GUI" with instructions on how to use the new GUI. Include a brief description of the GUI and its features. Update the dependencies section to include `tkinter`.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/rupeshs/neuralsongstyle?shareId=ef177903-b258-4993-aab8-397855070820).

### CODE REVIEW

**Comment by rupeshs** [comment]
@ticklecatisback  Thanks for this PR

**Review by rupeshs — APPROVED** [review]

**Comment by ticklecatisback** [comment]
Hello, this is a test from my GitHub Copilot preview. I just got access yesterday and am just testing it all around, so you can ignore this or use this PR. It has some bugs and errors that I'm trying to fix or might remove, but thanks for the answer anyways.

**Comment by rupeshs** [comment]
@ticklecatisback When it is ready feel free to create a PR. Also always commit with a message. Thanks.

**Comment by ticklecatisback** [comment]
okay no problem

**Pull request merged**
